// AUTO-GENERATED by scripts/infra/dev/generate_universe_ts.py
// Do not hand-edit. Source of truth: src/xenon/execution/universe.py
// Regenerate with: python3.13 scripts/infra/dev/generate_universe_ts.py

export type UniverseType = "INDEX" | "ETF";

export interface UniverseEntry {
  readonly ticker: string;
  readonly type: UniverseType;
  readonly isIndex: boolean;
  readonly cashSettled: boolean;
  readonly multiplier: number;
  readonly k1: boolean;
}


export const UNIVERSE: Readonly<Record<string, UniverseEntry>> = {
  GLD: { ticker: "GLD", type: "ETF", isIndex: false, cashSettled: false, multiplier: 100, k1: false },
  IWM: { ticker: "IWM", type: "ETF", isIndex: false, cashSettled: false, multiplier: 100, k1: false },
  NDX: { ticker: "NDX", type: "INDEX", isIndex: true, cashSettled: true, multiplier: 100, k1: false },
  QQQ: { ticker: "QQQ", type: "ETF", isIndex: false, cashSettled: false, multiplier: 100, k1: false },
  RUT: { ticker: "RUT", type: "INDEX", isIndex: true, cashSettled: true, multiplier: 100, k1: false },
  SIL: { ticker: "SIL", type: "ETF", isIndex: false, cashSettled: false, multiplier: 100, k1: false },
  SPX: { ticker: "SPX", type: "INDEX", isIndex: true, cashSettled: true, multiplier: 100, k1: false },
  SPY: { ticker: "SPY", type: "ETF", isIndex: false, cashSettled: false, multiplier: 100, k1: false },
  USO: { ticker: "USO", type: "ETF", isIndex: false, cashSettled: false, multiplier: 100, k1: true },
};

export const INDEX_UNIVERSE: ReadonlySet<string> = new Set(['NDX', 'RUT', 'SPX']);

export function isKnown(ticker: string): boolean {
  return Object.prototype.hasOwnProperty.call(UNIVERSE, ticker);
}

export function isIndex(ticker: string): boolean {
  const entry = UNIVERSE[ticker];
  if (!entry) throw new Error(`ticker ${ticker} not in V1 universe`);
  return entry.isIndex;
}

export function getMultiplier(ticker: string): number {
  const entry = UNIVERSE[ticker];
  if (!entry) throw new Error(`ticker ${ticker} not in V1 universe`);
  return entry.multiplier;
}
