"""normalize_payloads

Revision ID: 008128225148
Revises: 27a1d085c2cd
Create Date: 2026-04-27 02:05:48.053661

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "008128225148"
down_revision: Union[str, Sequence[str], None] = "27a1d085c2cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Wipe stale uw_analyze_snapshots rows: existing rows are written under the
    # old (vrp_state/regime/flow_signals) shape and would become NULL placeholders
    # after the column drops, then conflict with the disk-archive backfill.
    # On-disk archives in data/uw_analyze_history/ are the lossless source.
    op.execute("TRUNCATE TABLE xenon.uw_analyze_snapshots RESTART IDENTITY CASCADE;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gex_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("data_date", sa.Date(), nullable=True),
        sa.Column("scanned_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "spot",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(payload->>'spot')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "net_gex",
            sa.Numeric(precision=14, scale=2),
            sa.Computed("(payload->>'net_gex')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "net_dex",
            sa.Numeric(precision=14, scale=2),
            sa.Computed("(payload->>'net_dex')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "vol_pc",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(payload->>'vol_pc')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "iv_30d",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("((payload->'iv')->>'iv30d')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "iv_rank",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((payload->'iv')->>'iv_rank')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "hv_30d",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("((payload->'iv')->>'hv30')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "mq_iv_30d",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("((payload->'iv')->>'mq_iv30d')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_max_magnet_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(((payload->'levels')->'max_magnet')->>'strike')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_max_magnet_gamma",
            sa.Numeric(precision=14, scale=4),
            sa.Computed("(((payload->'levels')->'max_magnet')->>'gamma')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_second_magnet_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(((payload->'levels')->'second_magnet')->>'strike')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_second_magnet_gamma",
            sa.Numeric(precision=14, scale=4),
            sa.Computed("(((payload->'levels')->'second_magnet')->>'gamma')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_max_accelerator_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(((payload->'levels')->'max_accelerator')->>'strike')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_max_accelerator_gamma",
            sa.Numeric(precision=14, scale=4),
            sa.Computed("(((payload->'levels')->'max_accelerator')->>'gamma')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_put_wall_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(((payload->'levels')->'put_wall')->>'strike')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_call_wall_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(((payload->'levels')->'call_wall')->>'strike')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "level_gex_flip_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(((payload->'levels')->'gex_flip')->>'strike')::numeric", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_index("ix_gex_data_date", "gex_snapshots", ["data_date"], unique=False, schema="xenon")
    op.create_index("ix_gex_scanned_at", "gex_snapshots", ["scanned_at"], unique=False, schema="xenon")
    op.create_index("ix_gex_ticker_time", "gex_snapshots", ["ticker", "scanned_at"], unique=False, schema="xenon")
    op.create_table(
        "vcg_series",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("scanned_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("market_open", sa.Boolean(), nullable=True),
        sa.Column("credit_proxy", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "vcg",
            sa.Numeric(precision=10, scale=6),
            sa.Computed("((payload->'signal')->>'vcg')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "vcg_adj",
            sa.Numeric(precision=10, scale=6),
            sa.Computed("((payload->'signal')->>'vcg_adj')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "residual",
            sa.Numeric(precision=12, scale=8),
            sa.Computed("((payload->'signal')->>'residual')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "beta1_vvix",
            sa.Numeric(precision=12, scale=8),
            sa.Computed("((payload->'signal')->>'beta1_vvix')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "beta2_vix",
            sa.Numeric(precision=12, scale=8),
            sa.Computed("((payload->'signal')->>'beta2_vix')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "alpha",
            sa.Numeric(precision=12, scale=8),
            sa.Computed("((payload->'signal')->>'alpha')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "vix",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((payload->'signal')->>'vix')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "vvix",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((payload->'signal')->>'vvix')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "credit_price",
            sa.Numeric(precision=10, scale=4),
            sa.Computed("((payload->'signal')->>'credit_price')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "credit_5d_return_pct",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((payload->'signal')->>'credit_5d_return_pct')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "ro", sa.SmallInteger(), sa.Computed("((payload->'signal')->>'ro')::int", persisted=True), nullable=True
        ),
        sa.Column(
            "edr", sa.SmallInteger(), sa.Computed("((payload->'signal')->>'edr')::int", persisted=True), nullable=True
        ),
        sa.Column(
            "tier", sa.SmallInteger(), sa.Computed("((payload->'signal')->>'tier')::int", persisted=True), nullable=True
        ),
        sa.Column(
            "bounce",
            sa.SmallInteger(),
            sa.Computed("((payload->'signal')->>'bounce')::int", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "vvix_severity",
            sa.Text(),
            sa.Computed("(payload->'signal')->>'vvix_severity'", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "sign_ok",
            sa.Boolean(),
            sa.Computed("((payload->'signal')->>'sign_ok')::boolean", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "sign_suppressed",
            sa.Boolean(),
            sa.Computed("((payload->'signal')->>'sign_suppressed')::boolean", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "pi_panic",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((payload->'signal')->>'pi_panic')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column("regime", sa.Text(), sa.Computed("(payload->'signal')->>'regime'", persisted=True), nullable=True),
        sa.Column(
            "interpretation",
            sa.Text(),
            sa.Computed("(payload->'signal')->>'interpretation'", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "attr_vvix_pct",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((payload->'signal'->'attribution')->>'vvix_pct')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "attr_vix_pct",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((payload->'signal'->'attribution')->>'vix_pct')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "attr_vvix_component",
            sa.Numeric(precision=12, scale=8),
            sa.Computed("((payload->'signal'->'attribution')->>'vvix_component')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "attr_vix_component",
            sa.Numeric(precision=12, scale=8),
            sa.Computed("((payload->'signal'->'attribution')->>'vix_component')::numeric", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "attr_model_implied",
            sa.Numeric(precision=12, scale=8),
            sa.Computed("((payload->'signal'->'attribution')->>'model_implied')::numeric", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scanned_at", name="uq_vcg_series_scanned_at"),
        schema="xenon",
    )
    op.create_index("ix_vcg_regime", "vcg_series", ["regime"], unique=False, schema="xenon")
    op.create_index("ix_vcg_scanned_at", "vcg_series", ["scanned_at"], unique=False, schema="xenon")
    op.create_index(
        "ix_vcg_tier",
        "vcg_series",
        ["tier"],
        unique=False,
        schema="xenon",
        postgresql_where=sa.text("tier IS NOT NULL"),
    )
    op.create_table(
        "uw_analyze_flow_alerts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("snapshot_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("alert_type", sa.Text(), nullable=True),
        sa.Column("alert_severity", sa.Text(), nullable=True),
        sa.Column("alert_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["snapshot_id"], ["xenon.uw_analyze_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "ordinal", name="uq_uw_flow_alerts_snapshot_ordinal"),
        schema="xenon",
    )
    op.create_index(
        "ix_uw_flow_alerts_snapshot", "uw_analyze_flow_alerts", ["snapshot_id"], unique=False, schema="xenon"
    )
    op.create_index(
        "ix_uw_flow_alerts_ticker_time",
        "uw_analyze_flow_alerts",
        ["ticker", "snapshot_at"],
        unique=False,
        schema="xenon",
    )
    op.create_table(
        "uw_analyze_gex_strikes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("snapshot_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("strike", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("call_gamma", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("put_gamma", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("net_gamma", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("distance_pct", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("is_call_wall", sa.Boolean(), nullable=True),
        sa.Column("is_put_wall", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["snapshot_id"], ["xenon.uw_analyze_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "strike", name="uq_uw_gex_strikes_snapshot_strike"),
        schema="xenon",
    )
    op.create_index(
        "ix_uw_gex_strikes_snapshot", "uw_analyze_gex_strikes", ["snapshot_id"], unique=False, schema="xenon"
    )
    op.create_index(
        "ix_uw_gex_strikes_ticker_time",
        "uw_analyze_gex_strikes",
        ["ticker", "snapshot_at"],
        unique=False,
        schema="xenon",
    )
    op.create_table(
        "uw_analyze_short_volume_trend",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("snapshot_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("position_in_trend", sa.Integer(), nullable=False),
        sa.Column("ratio", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.ForeignKeyConstraint(["snapshot_id"], ["xenon.uw_analyze_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "position_in_trend", name="uq_uw_short_vol_snapshot_pos"),
        schema="xenon",
    )
    op.create_index(
        "ix_uw_short_vol_snapshot", "uw_analyze_short_volume_trend", ["snapshot_id"], unique=False, schema="xenon"
    )
    op.create_table(
        "uw_flow_event_ticks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("flow_event_key", sa.Text(), nullable=False),
        sa.Column("observed_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("track_date", sa.Date(), nullable=True),
        sa.Column("oi", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("mid", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("underlying_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("pct_change_premium", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("tick_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["xenon.uw_flow_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "observed_at", name="uq_uw_flow_event_ticks"),
        schema="xenon",
    )
    op.create_index(
        "ix_uw_flow_event_ticks_event_time",
        "uw_flow_event_ticks",
        ["event_id", "observed_at"],
        unique=False,
        schema="xenon",
    )
    op.create_index(
        "ix_uw_flow_event_ticks_observed_at", "uw_flow_event_ticks", ["observed_at"], unique=False, schema="xenon"
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "recorded_date",
            sa.Date(),
            sa.Computed(
                "make_date(split_part(payload->>'date','-',1)::int, split_part(payload->>'date','-',2)::int, split_part(payload->>'date','-',3)::int)",
                persisted=True,
            ),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "vix",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(payload->>'vix')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "vvix",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(payload->>'vvix')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "spy",
            sa.Numeric(precision=10, scale=4),
            sa.Computed("(payload->>'spy')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "vix_5d_roc",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(payload->>'vix_5d_roc')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "vvix_vix_ratio",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(payload->>'vvix_vix_ratio')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "spx_100d_ma",
            sa.Numeric(precision=10, scale=4),
            sa.Computed("(payload->>'spx_100d_ma')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "spx_distance_pct",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(payload->>'spx_distance_pct')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cor1m",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("(payload->>'cor1m')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cor1m_previous_close",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("(payload->>'cor1m_previous_close')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cor1m_5d_change",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("(payload->>'cor1m_5d_change')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "realized_vol",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(payload->>'realized_vol')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cri_score",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((payload->'cri')->>'score')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cri_components",
            postgresql.JSONB(astext_type=sa.Text()),
            sa.Computed("payload->'cri'->'components'", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cta_exposure_pct",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((payload->'cta')->>'exposure_pct')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cta_forced_reduction",
            sa.Boolean(),
            sa.Computed("((payload->'cta')->>'forced_reduction')::boolean", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "cta_selling_usd_b",
            sa.Numeric(precision=8, scale=2),
            sa.Computed("((payload->'cta')->>'selling_usd_b')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "menthorq_cta_score",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((payload->'menthorq_cta')->>'score')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "cri_series",
        sa.Column(
            "crash_trigger_fired",
            sa.Boolean(),
            sa.Computed("((payload->'crash_trigger')->>'fired')::boolean", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.create_index(
        "ix_cri_crash_trigger",
        "cri_series",
        ["crash_trigger_fired"],
        unique=False,
        schema="xenon",
        postgresql_where=sa.text("crash_trigger_fired"),
    )
    op.create_index(
        "ix_cri_cta_forced",
        "cri_series",
        ["cta_forced_reduction"],
        unique=False,
        schema="xenon",
        postgresql_where=sa.text("cta_forced_reduction"),
    )
    op.create_index("ix_cri_recorded_date", "cri_series", ["recorded_date"], unique=False, schema="xenon")
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("display", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("derived", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("dark_pool_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("options_flow_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("flow_alerts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("materialized_changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("report_fetched_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("archived_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "price",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(report->>'price')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "composite_score",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'scores')->>'composite')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "flow_score",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'scores')->>'flow')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "volatility_score",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'scores')->>'volatility')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "market_structure_score",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'scores')->>'market_structure')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "positioning_score",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'scores')->>'positioning')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("grade", sa.Text(), sa.Computed("(report->'scores')->>'grade'", persisted=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("bias", sa.Text(), sa.Computed("(report->'scores')->>'bias'", persisted=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("mode", sa.Text(), sa.Computed("(report->'scores')->>'mode'", persisted=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "reweighted",
            sa.Boolean(),
            sa.Computed("((report->'scores')->>'reweighted')::boolean", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "vrp_raw",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((report->'vrp')->>'vrp_raw')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "vrp_zscore",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((report->'vrp')->>'vrp_zscore')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "iv_percentile",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'vrp')->>'iv_percentile')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "ts_ratio",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((report->'vrp')->>'ts_ratio')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "ts_inverted",
            sa.Boolean(),
            sa.Computed("((report->'vrp')->>'ts_inverted')::boolean", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "earnings_within_14d",
            sa.Boolean(),
            sa.Computed("((report->'vrp')->>'earnings_within_14d')::boolean", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "regime_label", sa.Text(), sa.Computed("(report->'regime')->>'regime'", persisted=True), nullable=True
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "regime_reason", sa.Text(), sa.Computed("(report->'regime')->>'reason'", persisted=True), nullable=True
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("gex_sign", sa.Text(), sa.Computed("(report->'regime')->>'gex_sign'", persisted=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "gex_flip_relative",
            sa.Text(),
            sa.Computed("(report->'regime')->>'gex_flip_relative'", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "flip_distance_pct",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("((report->'regime')->>'flip_distance_pct')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "iv",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(display->>'iv')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "rv",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(display->>'rv')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "iv_rank",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("(display->>'iv_rank')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "call_wall_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(display->>'call_wall_strike')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "put_wall_strike",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(display->>'put_wall_strike')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "gamma_per_1pct",
            sa.Numeric(precision=18, scale=4),
            sa.Computed("(display->>'gamma_per_1pct')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "net_call_premium",
            sa.Numeric(precision=18, scale=2),
            sa.Computed("(display->>'net_call_premium')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "net_put_premium",
            sa.Numeric(precision=18, scale=2),
            sa.Computed("(display->>'net_put_premium')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "short_volume_ratio",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("(display->>'short_volume_ratio')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "term_structure_label",
            sa.Text(),
            sa.Computed("display->>'term_structure_label'", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "max_pain",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(display->>'max_pain')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("derived_gex_sign", sa.Text(), sa.Computed("derived->>'gex_sign'", persisted=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "derived_call_wall",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(derived->>'call_wall')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "derived_put_wall",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(derived->>'put_wall')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "derived_max_pain",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(derived->>'max_pain')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "derived_spot",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(derived->>'spot')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "dp_score",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(dark_pool_summary->>'score')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("dp_signal", sa.Text(), sa.Computed("dark_pool_summary->>'signal'", persisted=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "dp_direction", sa.Text(), sa.Computed("dark_pool_summary->>'direction'", persisted=True), nullable=True
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "dp_strength",
            sa.Integer(),
            sa.Computed("(dark_pool_summary->>'strength')::numeric::int", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "dp_buy_ratio",
            sa.Numeric(precision=6, scale=4),
            sa.Computed("(dark_pool_summary->>'buy_ratio')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "dp_options_conflict",
            sa.Boolean(),
            sa.Computed("(dark_pool_summary->>'options_conflict')::boolean", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "dp_num_prints",
            sa.Integer(),
            sa.Computed("(dark_pool_summary->>'num_prints')::numeric::int", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "dp_sustained_days",
            sa.Integer(),
            sa.Computed("(dark_pool_summary->>'sustained_days')::numeric::int", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "of_total_alerts",
            sa.Integer(),
            sa.Computed("(options_flow_summary->>'total_alerts')::numeric::int", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "of_total_premium",
            sa.Numeric(precision=18, scale=2),
            sa.Computed("(options_flow_summary->>'total_premium')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "of_call_premium",
            sa.Numeric(precision=18, scale=2),
            sa.Computed("(options_flow_summary->>'call_premium')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "of_put_premium",
            sa.Numeric(precision=18, scale=2),
            sa.Computed("(options_flow_summary->>'put_premium')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "of_call_put_ratio",
            sa.Numeric(precision=8, scale=4),
            sa.Computed("(options_flow_summary->>'call_put_ratio')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("of_bias", sa.Text(), sa.Computed("options_flow_summary->>'bias'", persisted=True), nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "spy_iv_rank",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'benchmark'->'spy')->>'iv_rank')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "spy_gex_regime",
            sa.Text(),
            sa.Computed("(report->'benchmark'->'spy')->>'gex_regime'", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "sector_etf_ticker",
            sa.Text(),
            sa.Computed("(report->'benchmark'->'sector_etf')->>'ticker'", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "sector_etf_iv_rank",
            sa.Numeric(precision=6, scale=2),
            sa.Computed("((report->'benchmark'->'sector_etf')->>'iv_rank')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column(
            "sector_etf_gex_regime",
            sa.Text(),
            sa.Computed("(report->'benchmark'->'sector_etf')->>'gex_regime'", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.create_index(
        "ix_uw_analyze_snap_time_bias", "uw_analyze_snapshots", ["snapshot_at", "bias"], unique=False, schema="xenon"
    )
    op.create_index(
        "ix_uw_analyze_snap_time_gex", "uw_analyze_snapshots", ["snapshot_at", "gex_sign"], unique=False, schema="xenon"
    )
    op.create_index(
        "ix_uw_analyze_snap_time_regime",
        "uw_analyze_snapshots",
        ["snapshot_at", "regime_label"],
        unique=False,
        schema="xenon",
    )
    op.drop_column("uw_analyze_snapshots", "vrp_state", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "flow_signals", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "regime", schema="xenon")
    op.add_column(
        "uw_flow_events",
        sa.Column(
            "initial_premium_usd",
            sa.Numeric(precision=14, scale=2),
            sa.Computed("(initial->>'premium_usd')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_flow_events",
        sa.Column(
            "initial_oi", sa.Integer(), sa.Computed("(initial->>'oi')::numeric::int", persisted=True), nullable=True
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_flow_events",
        sa.Column(
            "initial_volume",
            sa.Integer(),
            sa.Computed("(initial->>'volume')::numeric::int", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_flow_events",
        sa.Column(
            "initial_mid",
            sa.Numeric(precision=10, scale=4),
            sa.Computed("(initial->>'mid')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    op.add_column(
        "uw_flow_events",
        sa.Column(
            "initial_underlying_price",
            sa.Numeric(precision=12, scale=4),
            sa.Computed("(initial->>'underlying_price')::numeric", persisted=True),
            nullable=True,
        ),
        schema="xenon",
    )
    # ### end Alembic commands ###

    # ===== Trigger 1: uw_analyze_flow_alerts fanout =====
    op.execute("""
    CREATE OR REPLACE FUNCTION xenon.fanout_uw_analyze_flow_alerts() RETURNS TRIGGER AS $$
    DECLARE
      alert jsonb;
      pos int := 0;
    BEGIN
      IF NEW.flow_alerts IS NULL OR jsonb_typeof(NEW.flow_alerts) <> 'array' THEN
        RETURN NEW;
      END IF;
      FOR alert IN SELECT * FROM jsonb_array_elements(NEW.flow_alerts) LOOP
        INSERT INTO xenon.uw_analyze_flow_alerts (
          snapshot_id, ordinal, ticker, snapshot_at, alert_type, alert_severity, alert_payload
        ) VALUES (
          NEW.id, pos, NEW.ticker, NEW.snapshot_at,
          alert->>'type', alert->>'severity', alert
        )
        ON CONFLICT (snapshot_id, ordinal) DO UPDATE SET
          ticker = EXCLUDED.ticker,
          snapshot_at = EXCLUDED.snapshot_at,
          alert_type = EXCLUDED.alert_type,
          alert_severity = EXCLUDED.alert_severity,
          alert_payload = EXCLUDED.alert_payload;
        pos := pos + 1;
      END LOOP;
      DELETE FROM xenon.uw_analyze_flow_alerts
        WHERE snapshot_id = NEW.id AND ordinal >= pos;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trg_uw_analyze_flow_alerts_fanout
    AFTER INSERT OR UPDATE OF flow_alerts ON xenon.uw_analyze_snapshots
    FOR EACH ROW EXECUTE FUNCTION xenon.fanout_uw_analyze_flow_alerts();
    """)

    # ===== Trigger 2: uw_analyze_gex_strikes fanout =====
    op.execute("""
    CREATE OR REPLACE FUNCTION xenon.fanout_uw_analyze_gex_strikes() RETURNS TRIGGER AS $$
    DECLARE strike_row jsonb; seen_strikes numeric[] := ARRAY[]::numeric[]; s numeric;
    BEGIN
      IF NEW.display IS NULL OR (NEW.display->'gex_by_strike') IS NULL THEN
        RETURN NEW;
      END IF;
      IF jsonb_typeof(NEW.display->'gex_by_strike') <> 'array' THEN
        RETURN NEW;
      END IF;
      FOR strike_row IN SELECT * FROM jsonb_array_elements(NEW.display->'gex_by_strike') LOOP
        s := (strike_row->>'strike')::numeric;
        seen_strikes := array_append(seen_strikes, s);
        INSERT INTO xenon.uw_analyze_gex_strikes (
          snapshot_id, ticker, snapshot_at, strike,
          call_gamma, put_gamma, net_gamma, distance_pct,
          is_call_wall, is_put_wall
        ) VALUES (
          NEW.id, NEW.ticker, NEW.snapshot_at, s,
          (strike_row->>'call_gamma')::numeric,
          (strike_row->>'put_gamma')::numeric,
          (strike_row->>'net_gamma')::numeric,
          (strike_row->>'distance_pct')::numeric,
          (strike_row->>'is_call_wall')::boolean,
          (strike_row->>'is_put_wall')::boolean
        )
        ON CONFLICT (snapshot_id, strike) DO UPDATE SET
          call_gamma = EXCLUDED.call_gamma,
          put_gamma = EXCLUDED.put_gamma,
          net_gamma = EXCLUDED.net_gamma,
          distance_pct = EXCLUDED.distance_pct,
          is_call_wall = EXCLUDED.is_call_wall,
          is_put_wall = EXCLUDED.is_put_wall;
      END LOOP;
      DELETE FROM xenon.uw_analyze_gex_strikes
        WHERE snapshot_id = NEW.id AND NOT (strike = ANY(seen_strikes));
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trg_uw_analyze_gex_strikes_fanout
    AFTER INSERT OR UPDATE OF display ON xenon.uw_analyze_snapshots
    FOR EACH ROW EXECUTE FUNCTION xenon.fanout_uw_analyze_gex_strikes();
    """)

    # ===== Trigger 3: uw_analyze_short_volume_trend fanout =====
    op.execute("""
    CREATE OR REPLACE FUNCTION xenon.fanout_uw_analyze_short_volume_trend() RETURNS TRIGGER AS $$
    DECLARE
      ratio_val jsonb;
      pos int := 0;
    BEGIN
      IF NEW.display IS NULL OR (NEW.display->'short_volume_trend') IS NULL THEN
        RETURN NEW;
      END IF;
      IF jsonb_typeof(NEW.display->'short_volume_trend') <> 'array' THEN
        RETURN NEW;
      END IF;
      FOR ratio_val IN SELECT * FROM jsonb_array_elements(NEW.display->'short_volume_trend') LOOP
        INSERT INTO xenon.uw_analyze_short_volume_trend (
          snapshot_id, ticker, snapshot_at, position_in_trend, ratio
        ) VALUES (
          NEW.id, NEW.ticker, NEW.snapshot_at, pos, (ratio_val#>>'{}')::numeric
        )
        ON CONFLICT (snapshot_id, position_in_trend) DO UPDATE SET
          ticker = EXCLUDED.ticker,
          snapshot_at = EXCLUDED.snapshot_at,
          ratio = EXCLUDED.ratio;
        pos := pos + 1;
      END LOOP;
      DELETE FROM xenon.uw_analyze_short_volume_trend
        WHERE snapshot_id = NEW.id AND position_in_trend >= pos;
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trg_uw_analyze_short_volume_trend_fanout
    AFTER INSERT OR UPDATE OF display ON xenon.uw_analyze_snapshots
    FOR EACH ROW EXECUTE FUNCTION xenon.fanout_uw_analyze_short_volume_trend();
    """)

    # ===== Trigger 4: uw_flow_event_ticks fanout =====
    op.execute("""
    CREATE OR REPLACE FUNCTION xenon.fanout_uw_flow_event_ticks() RETURNS TRIGGER AS $$
    DECLARE
      tick jsonb;
      observed timestamptz;
      track_d date;
      seen_ts timestamptz[] := ARRAY[]::timestamptz[];
    BEGIN
      IF NEW.daily_track IS NULL THEN
        RETURN NEW;
      END IF;
      IF jsonb_typeof(NEW.daily_track) = 'array' THEN
        FOR tick IN SELECT * FROM jsonb_array_elements(NEW.daily_track) LOOP
          track_d := (tick->>'date')::date;
          observed := (track_d::timestamp + INTERVAL '20 hours') AT TIME ZONE 'UTC';
          seen_ts := array_append(seen_ts, observed);
          INSERT INTO xenon.uw_flow_event_ticks (
            event_id, flow_event_key, observed_at, track_date,
            oi, volume, mid, underlying_price, pct_change_premium, tick_payload
          ) VALUES (
            NEW.id, NEW.flow_event_key, observed, track_d,
            (tick->>'oi')::int,
            (tick->>'volume')::int,
            (tick->>'mid')::numeric,
            (tick->>'underlying_price')::numeric,
            (tick->>'pct_change_premium')::numeric,
            tick
          )
          ON CONFLICT (event_id, observed_at) DO UPDATE SET
            track_date = EXCLUDED.track_date,
            oi = EXCLUDED.oi,
            volume = EXCLUDED.volume,
            mid = EXCLUDED.mid,
            underlying_price = EXCLUDED.underlying_price,
            pct_change_premium = EXCLUDED.pct_change_premium,
            tick_payload = EXCLUDED.tick_payload;
        END LOOP;
      ELSIF jsonb_typeof(NEW.daily_track) = 'object' THEN
        FOR observed, tick IN
          SELECT key::timestamptz, value FROM jsonb_each(NEW.daily_track)
        LOOP
          seen_ts := array_append(seen_ts, observed);
          INSERT INTO xenon.uw_flow_event_ticks (
            event_id, flow_event_key, observed_at, track_date,
            oi, volume, mid, underlying_price, pct_change_premium, tick_payload
          ) VALUES (
            NEW.id, NEW.flow_event_key, observed, observed::date,
            (tick->>'oi')::int,
            (tick->>'volume')::int,
            (tick->>'mid')::numeric,
            (tick->>'underlying_price')::numeric,
            (tick->>'pct_change_premium')::numeric,
            tick
          )
          ON CONFLICT (event_id, observed_at) DO UPDATE SET
            track_date = EXCLUDED.track_date,
            oi = EXCLUDED.oi,
            volume = EXCLUDED.volume,
            mid = EXCLUDED.mid,
            underlying_price = EXCLUDED.underlying_price,
            pct_change_premium = EXCLUDED.pct_change_premium,
            tick_payload = EXCLUDED.tick_payload;
        END LOOP;
      END IF;
      DELETE FROM xenon.uw_flow_event_ticks
        WHERE event_id = NEW.id
          AND array_length(seen_ts, 1) IS NOT NULL
          AND NOT (observed_at = ANY(seen_ts));
      RETURN NEW;
    END $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trg_uw_flow_event_ticks_fanout
    AFTER INSERT OR UPDATE OF daily_track ON xenon.uw_flow_events
    FOR EACH ROW EXECUTE FUNCTION xenon.fanout_uw_flow_event_ticks();
    """)

    # ===== Backfill: replay triggers over existing rows =====
    # AFTER UPDATE OF <col> triggers fire only when <col> appears in the SET list.
    # `SET id = id` would touch the rows but NOT fire any of these triggers.
    op.execute("UPDATE xenon.uw_analyze_snapshots SET flow_alerts = flow_alerts WHERE flow_alerts IS NOT NULL;")
    op.execute("UPDATE xenon.uw_analyze_snapshots SET display = display WHERE display IS NOT NULL;")
    op.execute("UPDATE xenon.uw_flow_events SET daily_track = daily_track WHERE daily_track IS NOT NULL;")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_uw_flow_event_ticks_fanout ON xenon.uw_flow_events;")
    op.execute("DROP FUNCTION IF EXISTS xenon.fanout_uw_flow_event_ticks();")
    op.execute("DROP TRIGGER IF EXISTS trg_uw_analyze_short_volume_trend_fanout ON xenon.uw_analyze_snapshots;")
    op.execute("DROP FUNCTION IF EXISTS xenon.fanout_uw_analyze_short_volume_trend();")
    op.execute("DROP TRIGGER IF EXISTS trg_uw_analyze_gex_strikes_fanout ON xenon.uw_analyze_snapshots;")
    op.execute("DROP FUNCTION IF EXISTS xenon.fanout_uw_analyze_gex_strikes();")
    op.execute("DROP TRIGGER IF EXISTS trg_uw_analyze_flow_alerts_fanout ON xenon.uw_analyze_snapshots;")
    op.execute("DROP FUNCTION IF EXISTS xenon.fanout_uw_analyze_flow_alerts();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("uw_flow_events", "initial_underlying_price", schema="xenon")
    op.drop_column("uw_flow_events", "initial_mid", schema="xenon")
    op.drop_column("uw_flow_events", "initial_volume", schema="xenon")
    op.drop_column("uw_flow_events", "initial_oi", schema="xenon")
    op.drop_column("uw_flow_events", "initial_premium_usd", schema="xenon")
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("regime", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("flow_signals", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        schema="xenon",
    )
    op.add_column(
        "uw_analyze_snapshots",
        sa.Column("vrp_state", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        schema="xenon",
    )
    op.drop_index("ix_uw_analyze_snap_time_regime", table_name="uw_analyze_snapshots", schema="xenon")
    op.drop_index("ix_uw_analyze_snap_time_gex", table_name="uw_analyze_snapshots", schema="xenon")
    op.drop_index("ix_uw_analyze_snap_time_bias", table_name="uw_analyze_snapshots", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "sector_etf_gex_regime", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "sector_etf_iv_rank", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "sector_etf_ticker", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "spy_gex_regime", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "spy_iv_rank", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "of_bias", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "of_call_put_ratio", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "of_put_premium", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "of_call_premium", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "of_total_premium", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "of_total_alerts", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_sustained_days", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_num_prints", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_options_conflict", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_buy_ratio", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_strength", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_direction", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_signal", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dp_score", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "derived_spot", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "derived_max_pain", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "derived_put_wall", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "derived_call_wall", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "derived_gex_sign", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "max_pain", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "term_structure_label", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "short_volume_ratio", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "net_put_premium", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "net_call_premium", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "gamma_per_1pct", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "put_wall_strike", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "call_wall_strike", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "iv_rank", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "rv", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "iv", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "flip_distance_pct", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "gex_flip_relative", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "gex_sign", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "regime_reason", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "regime_label", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "earnings_within_14d", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "ts_inverted", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "ts_ratio", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "iv_percentile", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "vrp_zscore", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "vrp_raw", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "reweighted", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "mode", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "bias", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "grade", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "positioning_score", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "market_structure_score", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "volatility_score", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "flow_score", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "composite_score", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "price", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "archived_at", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "report_fetched_at", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "materialized_changes", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "flow_alerts", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "options_flow_summary", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "dark_pool_summary", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "derived", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "display", schema="xenon")
    op.drop_column("uw_analyze_snapshots", "report", schema="xenon")
    op.drop_index("ix_cri_recorded_date", table_name="cri_series", schema="xenon")
    op.drop_index(
        "ix_cri_cta_forced", table_name="cri_series", schema="xenon", postgresql_where=sa.text("cta_forced_reduction")
    )
    op.drop_index(
        "ix_cri_crash_trigger", table_name="cri_series", schema="xenon", postgresql_where=sa.text("crash_trigger_fired")
    )
    op.drop_column("cri_series", "crash_trigger_fired", schema="xenon")
    op.drop_column("cri_series", "menthorq_cta_score", schema="xenon")
    op.drop_column("cri_series", "cta_selling_usd_b", schema="xenon")
    op.drop_column("cri_series", "cta_forced_reduction", schema="xenon")
    op.drop_column("cri_series", "cta_exposure_pct", schema="xenon")
    op.drop_column("cri_series", "cri_components", schema="xenon")
    op.drop_column("cri_series", "cri_score", schema="xenon")
    op.drop_column("cri_series", "realized_vol", schema="xenon")
    op.drop_column("cri_series", "cor1m_5d_change", schema="xenon")
    op.drop_column("cri_series", "cor1m_previous_close", schema="xenon")
    op.drop_column("cri_series", "cor1m", schema="xenon")
    op.drop_column("cri_series", "spx_distance_pct", schema="xenon")
    op.drop_column("cri_series", "spx_100d_ma", schema="xenon")
    op.drop_column("cri_series", "vvix_vix_ratio", schema="xenon")
    op.drop_column("cri_series", "vix_5d_roc", schema="xenon")
    op.drop_column("cri_series", "spy", schema="xenon")
    op.drop_column("cri_series", "vvix", schema="xenon")
    op.drop_column("cri_series", "vix", schema="xenon")
    op.drop_column("cri_series", "recorded_date", schema="xenon")
    op.drop_index("ix_uw_flow_event_ticks_observed_at", table_name="uw_flow_event_ticks", schema="xenon")
    op.drop_index("ix_uw_flow_event_ticks_event_time", table_name="uw_flow_event_ticks", schema="xenon")
    op.drop_table("uw_flow_event_ticks", schema="xenon")
    op.drop_index("ix_uw_short_vol_snapshot", table_name="uw_analyze_short_volume_trend", schema="xenon")
    op.drop_table("uw_analyze_short_volume_trend", schema="xenon")
    op.drop_index("ix_uw_gex_strikes_ticker_time", table_name="uw_analyze_gex_strikes", schema="xenon")
    op.drop_index("ix_uw_gex_strikes_snapshot", table_name="uw_analyze_gex_strikes", schema="xenon")
    op.drop_table("uw_analyze_gex_strikes", schema="xenon")
    op.drop_index("ix_uw_flow_alerts_ticker_time", table_name="uw_analyze_flow_alerts", schema="xenon")
    op.drop_index("ix_uw_flow_alerts_snapshot", table_name="uw_analyze_flow_alerts", schema="xenon")
    op.drop_table("uw_analyze_flow_alerts", schema="xenon")
    op.drop_index("ix_vcg_tier", table_name="vcg_series", schema="xenon", postgresql_where=sa.text("tier IS NOT NULL"))
    op.drop_index("ix_vcg_scanned_at", table_name="vcg_series", schema="xenon")
    op.drop_index("ix_vcg_regime", table_name="vcg_series", schema="xenon")
    op.drop_table("vcg_series", schema="xenon")
    op.drop_index("ix_gex_ticker_time", table_name="gex_snapshots", schema="xenon")
    op.drop_index("ix_gex_scanned_at", table_name="gex_snapshots", schema="xenon")
    op.drop_index("ix_gex_data_date", table_name="gex_snapshots", schema="xenon")
    op.drop_table("gex_snapshots", schema="xenon")
    # ### end Alembic commands ###
