"""initial schema

Revision ID: 0cf835b06d68
Revises:
Create Date: 2026-04-26 10:14:40.701095

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0cf835b06d68"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_schemas() -> None:
    """Create xenon/events schemas if the connected role has CREATE privilege.

    Schemas are normally pre-created by the DBA setup script. This is a
    convenience for fresh installs where the migration runner IS the superuser.
    If the role lacks CREATE privilege, the schemas must already exist.
    """
    from alembic import op as _op
    from sqlalchemy import text

    conn = _op.get_bind()
    for schema in ("xenon", "events"):
        exists = conn.execute(
            text("SELECT 1 FROM information_schema.schemata WHERE schema_name = :s"),
            {"s": schema},
        ).scalar()
        if not exists:
            try:
                conn.execute(text(f"CREATE SCHEMA {schema}"))
            except Exception as exc:
                raise RuntimeError(
                    f"Schema '{schema}' does not exist and this role cannot create it. "
                    f"Run the DBA setup script first (see CLAUDE.md § Startup Checklist)."
                ) from exc


def upgrade() -> None:
    """Upgrade schema."""
    _ensure_schemas()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("account", sa.Text(), nullable=False),
        sa.Column("bankroll", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("peak_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("net_liquidation", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("snapshot_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_table(
        "cri_series",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cri_level", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("alert", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recorded_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_table(
        "nav_history",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("nav", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("daily_pnl", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("date"),
        schema="xenon",
    )
    op.create_table(
        "order_submissions",
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("client_attempt_id", sa.Text(), nullable=True),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("security_type", sa.Text(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("right", sa.Text(), nullable=True),
        sa.Column("multiplier", sa.Integer(), server_default=sa.text("100"), nullable=True),
        sa.Column("con_id", sa.BigInteger(), nullable=True),
        sa.Column("placing_client_id", sa.Integer(), nullable=True),
        sa.Column("ib_order_id", sa.Text(), nullable=True),
        sa.Column("perm_id", sa.Text(), nullable=True),
        sa.Column("limit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("reason_code", sa.Text(), nullable=True),
        sa.Column("filled_qty", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("avg_fill_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("modify_sequence", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("submitted_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("submission_id"),
        sa.UniqueConstraint("user_id", "client_attempt_id", name="uq_order_sub_user_attempt"),
        schema="xenon",
    )
    op.create_index("ix_order_sub_ib_order_id", "order_submissions", ["ib_order_id"], unique=False, schema="xenon")
    op.create_index("ix_order_sub_perm_id", "order_submissions", ["perm_id"], unique=False, schema="xenon")
    op.create_index("ix_order_sub_state_ticker", "order_submissions", ["state", "ticker"], unique=False, schema="xenon")
    op.create_table(
        "positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("security_type", sa.Text(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("right", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("avg_cost", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("current_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unrealized_pnl", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("account", sa.Text(), nullable=False),
        sa.Column("synced_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_table(
        "scan_results",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("scan_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scanned_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_table(
        "ticker_cache",
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("cache_type", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("ticker", "cache_type"),
        schema="xenon",
    )
    op.create_table(
        "trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("structure", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_cost", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("exit_cost", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("edge", sa.Text(), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("opened_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("closed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_table(
        "uw_api_stats",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("bucket_hour", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("requests", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("cache_hits", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("latency_sum", sa.Numeric(precision=10, scale=2), server_default=sa.text("0"), nullable=True),
        sa.Column("latency_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("status_2xx", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("status_4xx", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("status_5xx", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket_hour"),
        schema="xenon",
    )
    op.create_table(
        "uw_flow_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=True),
        sa.Column("strike", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("detected_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("initial", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("daily_track", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("anomaly_reason", sa.Text(), nullable=True),
        sa.Column("closed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_table(
        "uw_snapshots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("vrp_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("regime", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("flow_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("portfolio_score", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("snapshot_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="xenon",
    )
    op.create_index("ix_uw_snap_ticker_time", "uw_snapshots", ["ticker", "snapshot_at"], unique=False, schema="xenon")
    op.create_table(
        "wizard_sessions",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("structure_name", sa.Text(), nullable=True),
        sa.Column("intent", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("current_attempt_id", sa.Text(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("session_id"),
        schema="xenon",
    )
    op.create_table(
        "order_events",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["xenon.order_submissions.submission_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        schema="xenon",
    )
    op.create_table(
        "wizard_combo_attempts",
        sa.Column("attempt_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("ticker", sa.Text(), nullable=False),
        sa.Column("structure_name", sa.Text(), nullable=True),
        sa.Column("legs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("combo_contract", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ib_order_id", sa.Text(), nullable=True),
        sa.Column("perm_id", sa.Text(), nullable=True),
        sa.Column("placing_client_id", sa.Integer(), nullable=True),
        sa.Column("limit_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("reason_code", sa.Text(), nullable=True),
        sa.Column("filled_qty", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("avg_fill_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("modify_sequence", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("submitted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["xenon.wizard_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("attempt_id"),
        schema="xenon",
    )
    op.create_table(
        "wizard_events",
        sa.Column("event_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["xenon.wizard_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
        schema="xenon",
    )
    op.create_table(
        "wizard_protection",
        sa.Column("protection_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("attempt_id", sa.Text(), nullable=True),
        sa.Column("protection_type", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.Text(), server_default=sa.text("'active'"), nullable=False),
        sa.Column("triggered_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["xenon.wizard_combo_attempts.attempt_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["xenon.wizard_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("protection_id"),
        schema="xenon",
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("emitted_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "consumed_by", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="events",
    )
    op.create_index("ix_outbox_channel_time", "outbox", ["channel", "emitted_at"], unique=False, schema="events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_channel_time", table_name="outbox", schema="events")
    op.drop_table("outbox", schema="events")
    op.drop_table("wizard_protection", schema="xenon")
    op.drop_table("wizard_events", schema="xenon")
    op.drop_table("wizard_combo_attempts", schema="xenon")
    op.drop_table("order_events", schema="xenon")
    op.drop_table("wizard_sessions", schema="xenon")
    op.drop_index("ix_uw_snap_ticker_time", table_name="uw_snapshots", schema="xenon")
    op.drop_table("uw_snapshots", schema="xenon")
    op.drop_table("uw_flow_events", schema="xenon")
    op.drop_table("uw_api_stats", schema="xenon")
    op.drop_table("trades", schema="xenon")
    op.drop_table("ticker_cache", schema="xenon")
    op.drop_table("scan_results", schema="xenon")
    op.drop_table("positions", schema="xenon")
    op.drop_index("ix_order_sub_state_ticker", table_name="order_submissions", schema="xenon")
    op.drop_index("ix_order_sub_perm_id", table_name="order_submissions", schema="xenon")
    op.drop_index("ix_order_sub_ib_order_id", table_name="order_submissions", schema="xenon")
    op.drop_table("order_submissions", schema="xenon")
    op.drop_table("nav_history", schema="xenon")
    op.drop_table("cri_series", schema="xenon")
    op.drop_table("account_snapshots", schema="xenon")
    # ### end Alembic commands ###
