"""add flex_divergence_runs

Revision ID: 4da18cde403f
Revises: abab65c8d193
Create Date: 2026-04-29 13:38:32.697958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4da18cde403f'
down_revision: Union[str, Sequence[str], None] = 'abab65c8d193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flex_divergence_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ran_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scope_broker', sa.Text(), nullable=False),
    sa.Column('scope_account_env', sa.Text(), nullable=False),
    sa.Column('scope_broker_account', sa.Text(), nullable=False),
    sa.Column('total_compared', sa.Integer(), nullable=False),
    sa.Column('divergence_count', sa.Integer(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='xenon'
    )
    op.create_index('ix_flex_divergence_scope_ran_at', 'flex_divergence_runs', ['scope_broker', 'scope_account_env', 'scope_broker_account', 'ran_at'], unique=False, schema='xenon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flex_divergence_scope_ran_at', table_name='flex_divergence_runs', schema='xenon')
    op.drop_table('flex_divergence_runs', schema='xenon')
    # ### end Alembic commands ###
