"""add flow_event_key to uw_flow_events

Revision ID: 560b7b076a15
Revises: 80e181cf1308
Create Date: 2026-04-26 15:24:08.615734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560b7b076a15'
down_revision: Union[str, Sequence[str], None] = '80e181cf1308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uw_flow_events', sa.Column('flow_event_key', sa.Text(), nullable=True), schema='xenon')
    op.create_unique_constraint(None, 'uw_flow_events', ['flow_event_key'], schema='xenon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uw_flow_events', schema='xenon', type_='unique')
    op.drop_column('uw_flow_events', 'flow_event_key', schema='xenon')
    # ### end Alembic commands ###
