"""add ib_cash_flow table

Revision ID: 58107314f4c9
Revises: 2026_06_03_nav_src_pk
Create Date: 2026-06-03 23:50:28.716475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58107314f4c9'
down_revision: Union[str, Sequence[str], None] = '2026_06_03_nav_src_pk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ib_cash_flow',
    sa.Column('broker', sa.Text(), nullable=False),
    sa.Column('account_env', sa.Text(), nullable=False),
    sa.Column('broker_account', sa.Text(), nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=False),
    sa.Column('txn_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_native', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_env IN ('paper', 'live', 'sim')", name='ck_ib_cash_flow_account_env'),
    sa.CheckConstraint("broker = 'IB'", name='ck_ib_cash_flow_broker'),
    sa.PrimaryKeyConstraint('broker', 'account_env', 'broker_account', 'transaction_id'),
    schema='xenon'
    )
    op.create_index('ix_ib_cash_flow_scope_occurred_at', 'ib_cash_flow', ['broker', 'account_env', 'broker_account', 'occurred_at'], unique=False, schema='xenon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ib_cash_flow_scope_occurred_at', table_name='ib_cash_flow', schema='xenon')
    op.drop_table('ib_cash_flow', schema='xenon')
    # ### end Alembic commands ###
