"""user_watchlist table

Revision ID: adaaa7ea740d
Revises: 0997cb7be148
Create Date: 2026-06-16 11:46:35.165392

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "adaaa7ea740d"
down_revision: Union[str, Sequence[str], None] = "0997cb7be148"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_watchlist",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("added_at", postgresql.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "symbol", name="uq_user_watchlist_user_symbol"),
        schema="xenon",
    )
    op.create_index(
        "ix_user_watchlist_user_added", "user_watchlist", ["user_id", "added_at"], unique=False, schema="xenon"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_watchlist_user_added", table_name="user_watchlist", schema="xenon")
    op.drop_table("user_watchlist", schema="xenon")
    # ### end Alembic commands ###
