"""add constraints and indexes from review

Revision ID: eaec7f146df5
Revises: 560b7b076a15
Create Date: 2026-04-26 19:20:44.596553

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eaec7f146df5"
down_revision: Union[str, Sequence[str], None] = "560b7b076a15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_order_events_submission_at", "order_events", ["submission_id", "at"], unique=False, schema="xenon"
    )
    op.alter_column("uw_flow_events", "flow_event_key", existing_type=sa.TEXT(), nullable=False, schema="xenon")
    op.create_index(
        "ix_wizard_attempts_session_updated",
        "wizard_combo_attempts",
        ["session_id", "updated_at"],
        unique=False,
        schema="xenon",
    )
    op.create_unique_constraint("uq_wizard_protection_session", "wizard_protection", ["session_id"], schema="xenon")
    op.create_check_constraint("ck_outbox_channel_length", "outbox", "length(channel) <= 63", schema="events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_wizard_protection_session", "wizard_protection", schema="xenon", type_="unique")
    op.drop_index("ix_wizard_attempts_session_updated", table_name="wizard_combo_attempts", schema="xenon")
    op.alter_column("uw_flow_events", "flow_event_key", existing_type=sa.TEXT(), nullable=True, schema="xenon")
    op.drop_index("ix_order_events_submission_at", table_name="order_events", schema="xenon")
    op.drop_constraint("ck_outbox_channel_length", "outbox", schema="events", type_="check")
    # ### end Alembic commands ###
