#!/usr/bin/env python3
"""Generate web/lib/universe.ts from src/xenon/execution/universe.py.

Runs as a prebuild/predev/pretest hook from web/package.json. The TS
file is marked generated in .gitattributes. Do not hand-edit.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Self-sufficient path setup — repo does not install `xenon` as an
# editable package. This script runs from npm hooks where PYTHONPATH
# is not guaranteed.
_HERE = Path(__file__).resolve()
# parents[0]=dev, [1]=infra, [2]=scripts, [3]=repo root
_REPO_ROOT = _HERE.parents[3]
assert (_REPO_ROOT / "web" / "package.json").exists(), (
    f"repo root detection failed; resolved {_REPO_ROOT} but no web/package.json there"
)
_SRC = _REPO_ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from xenon.execution.universe import INDEX_UNIVERSE, UNIVERSE  # noqa: E402

HEADER = """\
// AUTO-GENERATED by scripts/infra/dev/generate_universe_ts.py
// Do not hand-edit. Source of truth: src/xenon/execution/universe.py
// Regenerate with: python3.13 scripts/infra/dev/generate_universe_ts.py

export type UniverseType = "INDEX" | "ETF";

export interface UniverseEntry {
  readonly ticker: string;
  readonly type: UniverseType;
  readonly isIndex: boolean;
  readonly cashSettled: boolean;
  readonly multiplier: number;
  readonly k1: boolean;
}

"""


def render_entry(ticker: str) -> str:
    e = UNIVERSE[ticker]
    return (
        f'  {ticker}: {{ ticker: "{e.ticker}", type: "{e.type}", '
        f"isIndex: {str(e.is_index).lower()}, "
        f"cashSettled: {str(e.cash_settled).lower()}, "
        f"multiplier: {e.multiplier}, "
        f"k1: {str(e.k1).lower()} }},"
    )


def render() -> str:
    lines = [HEADER, "export const UNIVERSE: Readonly<Record<string, UniverseEntry>> = {"]
    for ticker in sorted(UNIVERSE.keys()):
        lines.append(render_entry(ticker))
    lines.append("};")
    lines.append("")
    lines.append(f"export const INDEX_UNIVERSE: ReadonlySet<string> = new Set({sorted(INDEX_UNIVERSE)!r});")
    lines.append("")
    lines.append("export function isKnown(ticker: string): boolean {")
    lines.append("  return Object.prototype.hasOwnProperty.call(UNIVERSE, ticker);")
    lines.append("}")
    lines.append("")
    lines.append("export function isIndex(ticker: string): boolean {")
    lines.append("  const entry = UNIVERSE[ticker];")
    lines.append("  if (!entry) throw new Error(`ticker ${ticker} not in V1 universe`);")
    lines.append("  return entry.isIndex;")
    lines.append("}")
    lines.append("")
    lines.append("export function getMultiplier(ticker: string): number {")
    lines.append("  const entry = UNIVERSE[ticker];")
    lines.append("  if (!entry) throw new Error(`ticker ${ticker} not in V1 universe`);")
    lines.append("  return entry.multiplier;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    out_path = _REPO_ROOT / "web" / "lib" / "universe.ts"
    out_path.write_text(render())
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
